import { Body, Controller, Get, Param, Patch, Post, Query, UseGuards } from '@nestjs/common';
import { ApiTags, ApiBearerAuth, ApiOperation } from '@nestjs/swagger';
import { JwtAuthGuard } from '../../common/guards/jwt-auth.guard';
import { RolesGuard } from '../../common/guards/roles.guard';
import { Roles } from '../../common/decorators/roles.decorator';
import { CurrentUser, CurrentUserPayload } from '../../common/decorators/current-user.decorator';
import { PromotedEngineService } from './promoted-engine.service';
import {
  ActiveBoostsQueryDto,
  CreateCampaignDto,
  RecordEventDto,
  UpdateCampaignStatusDto,
} from './dto/promoted-engine.dto';
import { PromotionTargetType } from '@prisma/client';
/**
 * Promoted Engine API — sponsored/boosted visibility for job postings,
 * proposals (applications), and gigs (freelance jobs).
 *
 * Campaign management endpoints (create/list/status/analytics) require
 * authentication and are restricted to EMPLOYER/FREELANCER/ADMIN, with an
 * ownership check on any single-campaign read/write.
 *
 * `events` and `active-boosts` are intentionally left OPEN (no JwtAuthGuard)
 * — impressions and clicks are generated by anonymous visitors browsing
 * public job/gig listings, and the boost lookup itself must be callable
 * from the public search page. Click-fraud protection (rate limiting per
 * IP/session, bot filtering) is a known follow-up, not implemented in this
 * first version — flagged here rather than silently assumed away.
 */
@ApiTags('promoted-engine')
@Controller('promoted-engine')
export class PromotedEngineController {
  constructor(private readonly promotedEngineService: PromotedEngineService) {}

  @Post('campaigns')
  @UseGuards(JwtAuthGuard, RolesGuard)
  @Roles('EMPLOYER', 'FREELANCER', 'ADMIN')
  @ApiBearerAuth()
  @ApiOperation({ summary: 'Create a new promotion campaign for a job, proposal, or gig.' })
  async createCampaign(@Body() dto: CreateCampaignDto, @CurrentUser() user: CurrentUserPayload) {
    return this.promotedEngineService.createCampaign(user.userId, dto);
  }

  @Get('campaigns/mine')
  @UseGuards(JwtAuthGuard, RolesGuard)
  @Roles('EMPLOYER', 'FREELANCER', 'ADMIN')
  @ApiBearerAuth()
  @ApiOperation({ summary: "List the caller's own campaigns." })
  async listMyCampaigns(@CurrentUser() user: CurrentUserPayload) {
    return this.promotedEngineService.listMyCampaigns(user.userId);
  }

  @Get('campaigns/:id')
  @UseGuards(JwtAuthGuard, RolesGuard)
  @Roles('EMPLOYER', 'FREELANCER', 'ADMIN')
  @ApiBearerAuth()
  @ApiOperation({ summary: 'Get a single campaign (owner or admin only).' })
  async getCampaign(@Param('id') id: string, @CurrentUser() user: CurrentUserPayload) {
    return this.promotedEngineService.getCampaign(id, user.userId, user.role);
  }

  @Patch('campaigns/:id/status')
  @UseGuards(JwtAuthGuard, RolesGuard)
  @Roles('EMPLOYER', 'FREELANCER', 'ADMIN')
  @ApiBearerAuth()
  @ApiOperation({ summary: 'Pause, resume, or cancel a campaign (owner or admin only).' })
  async updateStatus(
    @Param('id') id: string,
    @Body() dto: UpdateCampaignStatusDto,
    @CurrentUser() user: CurrentUserPayload,
  ) {
    return this.promotedEngineService.updateStatus(id, user.userId, user.role, dto.status);
  }

  @Get('campaigns/:id/analytics')
  @UseGuards(JwtAuthGuard, RolesGuard)
  @Roles('EMPLOYER', 'FREELANCER', 'ADMIN')
  @ApiBearerAuth()
  @ApiOperation({
    summary: 'Get impressions/clicks/conversions/spend for a campaign (owner or admin only).',
  })
  async getAnalytics(@Param('id') id: string, @CurrentUser() user: CurrentUserPayload) {
    return this.promotedEngineService.getAnalytics(id, user.userId, user.role);
  }

  @Post('campaigns/:id/events')
  @ApiOperation({
    summary:
      'Record an impression, click, or conversion against a campaign. No auth — called by anonymous viewers.',
  })
  async recordEvent(@Param('id') id: string, @Body() dto: RecordEventDto) {
    return this.promotedEngineService.recordEvent(id, dto.type);
  }

  @Get('active-boosts')
  @ApiOperation({
    summary:
      'Check which of a batch of targets currently have a winning active boost. No auth — used by the public search page.',
  })
  async getActiveBoosts(@Query() query: ActiveBoostsQueryDto) {
    const targetIds = query.targetIds
      .split(',')
      .map((id) => id.trim())
      .filter(Boolean);
    return this.promotedEngineService.getActiveBoosts(
      query.targetType as PromotionTargetType,
      targetIds,
    );
  }
}
