import { Inject, Injectable } from '@nestjs/common';
import * as crypto from 'crypto';
import { ENCRYPTION_KEY } from './encryption.constants';

@Injectable()
export class EncryptionService {
  private readonly ALGORITHM = 'aes-256-gcm';
  private readonly IV_LENGTH = 12;
  private readonly AUTH_TAG_LENGTH = 16;
  private readonly KEY_LENGTH = 32;

  constructor(
    @Inject(ENCRYPTION_KEY)
    private readonly key: Buffer,
  ) {
    if (this.key.length !== this.KEY_LENGTH) {
      throw new Error(
        `EncryptionService requires a ${this.KEY_LENGTH}-byte key, received ${this.key.length} bytes.`,
      );
    }
  }

  /**
   * Encrypt plaintext using AES-256-GCM.
   *
   * Payload format:
   * Base64(
   *   [IV][AUTH_TAG][CIPHERTEXT]
   * )
   */
  encrypt(plaintext: string): string {
    if (!plaintext.trim()) {
      throw new Error('Plaintext cannot be empty.');
    }

    try {
      const iv = crypto.randomBytes(this.IV_LENGTH);

      const cipher = crypto.createCipheriv(this.ALGORITHM, this.key, iv);

      const ciphertext = Buffer.concat([cipher.update(plaintext, 'utf8'), cipher.final()]);

      const authTag = cipher.getAuthTag();

      const payload = Buffer.concat([iv, authTag, ciphertext]);

      return payload.toString('base64');
    } catch {
      throw new Error('Message encryption failed.');
    }
  }

  /**
   * Decrypt a Base64 payload generated by encrypt().
   */
  decrypt(payload: string): string {
    try {
      const buffer = Buffer.from(payload, 'base64');

      if (buffer.length < this.IV_LENGTH + this.AUTH_TAG_LENGTH) {
        throw new Error('Invalid encrypted payload.');
      }

      const iv = buffer.subarray(0, this.IV_LENGTH);

      const authTag = buffer.subarray(this.IV_LENGTH, this.IV_LENGTH + this.AUTH_TAG_LENGTH);

      const ciphertext = buffer.subarray(this.IV_LENGTH + this.AUTH_TAG_LENGTH);

      const decipher = crypto.createDecipheriv(this.ALGORITHM, this.key, iv);

      decipher.setAuthTag(authTag);

      const plaintext = Buffer.concat([decipher.update(ciphertext), decipher.final()]);

      return plaintext.toString('utf8');
    } catch {
      throw new Error('Message decryption failed.');
    }
  }
}
